version: '3'
services:
  db:
    image: mysql:8
    platform: linux/amd64
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb_buffer_pool_size=2G --innodb_buffer_pool_instances=2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes: []
  solr:
    image: solr:8.11
    ports:
     - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - arclight
      - /opt/solr/server/solr/configsets/arclight
    volumes:
      - ./solr/conf:/opt/solr/server/solr/configsets/arclight/conf
