#!/bin/bash

PROVIDER=${1:-https://archivesspace.lyrasistechnology.org/oai}

docker run -it --rm --net=host \
  -e OAI_ENDPOINT=$PROVIDER \
  -e REPOSITORY_URL=https://s3-us-west-2.amazonaws.com/as-public-shared-files/dts/dts.repo.yml \
  -e SOLR_URL=http://localhost:8983/solr/arclight \
  lyrasis/arclight-oai-indexer:latest bundle exec rake arclight:index:oai[1970-01-01]
