default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123456
  host: <%= ENV.fetch('FADLIGHT_DATABASE_HOST', '127.0.0.1') %>

development:
  <<: *default
  database: fadlight_development

test:
  <<: *default
  database: fadlight_test

production:
  <<: *default
  database: <%= ENV['FADLIGHT_DATABASE_NAME'] %>
  username: <%= ENV['FADLIGHT_DATABASE_USERNAME'] %>
  password: <%= ENV['FADLIGHT_DATABASE_PASSWORD'] %>
