lyrasis_special_collections:
  identifier_prefix: "oai:demo//repositories/2/"
  name: "LYRASIS Special Collections"
  description: "LYRASIS Special Collections"
  building: "LYRASIS"
  address1: "1438 West Peachtree Street, NW, Ste 150"
  address2: ""
  city: "Atlanta"
  state: "GA"
  zip: "30309"
  country: "USA"
  phone: ""
  contact_info: ""
  thumbnail_url: "https://s3-us-west-2.amazonaws.com/as-public-shared-files/dts/dts.logo.png"
  visit_note: ""
